### ISSUE TITLE
Creating ubuntu custom image, gsutil not working

### ISSUE THREAD

**Issue by dmsolow** [GoogleCloudPlatform/cloud-dataproc#100]
I'm running the following command:
```
python2 generate_custom_image.py     --image-name test     --dataproc-version 1.4.5-ubuntu18     --customization-script local.sh     --daisy-path /home/user/daisy     --zone us-east1-c     --gcs-bucket gs://my-bucket
```
This fails. The relevant error in the serial output on the VM is here:
```
Jun  3 12:11:42 test-install-test-vbp23 startup-script: INFO startup-script-url: ERROR: (gsutil) /snap/google-cloud-sdk/79/usr/bin/python2: command not found
Jun  3 12:11:42 test-install-test-vbp23 startup-script: INFO startup-script-url: bash: ./init_actions.sh: No such file or directory
Jun  3 12:11:42 test-install-test-vbp23 startup-script: INFO startup-script-url: BuildFailed: Dataproc Initialization Actions Failed. Please check your initialization script.
```
It looks like the `gsutil` call in `run.sh` is failing. Any idea why this would be?

When I create a custom VM based on the dataproc image I'm using (`projects/cloud-dataproc/global/images/dataproc-1-4-ubu18-20190510-000000-rc01`) gsutil seems to work fine.

**Comment by functicons** [comment]
I reproduced the problem with a custom script which runs `gsutil`:

```
$ gsutil
ERROR: (gsutil) /snap/google-cloud-sdk/79/usr/bin/python2: command not found

$ which gsutil

$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

**Comment by dmsolow** [comment]
@functicons even if the custom script doesn't use `gsutil`, the `run.sh` script [here](https://github.com/GoogleCloudPlatform/cloud-dataproc/blob/master/custom-images/run.sh#L21) does use it

**Comment by functicons** [comment]
I saw this error in the serial port log:

```
Jun  4 00:29:03 my-ubuntu-image-install-my-ubuntu-image-mqytn startup-script: INFO startup-script-url: /snap/google-cloud-sdk/79/usr/bin/python2: relocation error: /lib/x86_64-linux-gnu/libnss_dns.so.2: symbol __resolv_context_get, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

Seems the problem has nothing to do with the contents of the custom script, but the tool failed to download the custom script from GCS staging bucket with gsutil.

**Comment by functicons** [comment]
@dmsolow I think I found a workaround, adding `sleep 30` before the [line](https://github.com/GoogleCloudPlatform/cloud-dataproc/blob/master/custom-images/run.sh#L21) running `gsutil`. Can you try? My theory is that, snap is mounted dynamically, `gsutil` was not ready at that point.

**Comment by dmsolow** [comment]
@functions this works for me. I added the following to `run.sh`:
```
while [ ! -d "/snap/" ]; do
    sleep 5
done
sleep 5
```

I have another unrelated question that I wonder if you could help with. When I build a dataproc cluster with version `1.4.5-ubuntu18` it comes with Python (miniconda specifically) installed. However when I try to create a custom image from `1.4.5-ubuntu18` the VM does not have miniconda installed. Any idea what's going on here?

I'm probably just misunderstanding what lives in the image.

**Comment by functicons** [comment]
@dmsolow Can you trying add `source /etc/profile.d/effective-python.sh` before running `conda update python -y` in your script?

**Comment by dmsolow** [comment]
@functicons that file does not exist:
```
daniel@dataproc-test:~$ ls /etc/profile.d/
01-locale-fix.sh  Z97-byobu.sh  Z99-cloud-locale-test.sh  Z99-cloudinit-warnings.sh  apps-bin-path.sh  bash_completion.sh  cedilla-portuguese.sh
```

There is a script with the same name: `/usr/local/share/google/dataproc/bdutil/components/shared/effective-python.sh`

But sourcing it doesn't seem to do anything, at least it doesn't add the conda command

**Comment by dmsolow** [comment]
It looks like `conda` is located at `/opt/conda/anaconda/pkgs/conda-4.6.14-py36_0/bin/conda`

I should be able to use the upgrade command with that file. Thanks for your help!
