### ISSUE TITLE
Dataproc Job Logs

### ISSUE THREAD

**Issue by hitesh1907nayyar** [GoogleCloudPlatform/cloud-dataproc#110]
Hi, 

I need to see the logs of a job that i submitted in Dataproc. It is a python script job that i need to debug. How can i see end to end logs for that python script job ?

**Comment by functicons** [comment]
In the Web UI, go to Dataproc > Jobs > [Job] > Output.

**Comment by KoopaKing** [comment]
Also if you want to view it in StackDriver, you can set properties on the cluster to have the Job logs (both driver and executors) exported there.
https://cloud.google.com/dataproc/docs/guides/stackdriver-logging#job_logs_in
