### ISSUE TITLE
Dataproc image version supporting Spark 2.3.0

### ISSUE THREAD

**Issue by nehalecky** [GoogleCloudPlatform/cloud-dataproc#47]
Hello! 

All of us at [Bombora](https://github.com/bomboradata) are curious and eager to begin using Spark 2.3.0 so we can leverage some of the [vectorized UDF enhancements](https://databricks.com/blog/2017/10/30/introducing-vectorized-udfs-for-pyspark.html) released with the new version. With this, I didn't see any update to the [preview images](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions), and we were wondering when should we expect a new dataproc image version including 2.3.0? 

FWIW, I did a quick check across [issues here](https://github.com/GoogleCloudPlatform/cloud-dataproc/issues), and also the [init actions repo](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions), but couldn't find any other issues requesting the same.

Appreciate any update, thank you!

**Comment by aniket486** [comment]
@nehalecky - Thanks for submitting this request.
Dataproc 1.3 supports Spark 2.3.0. You can find more details at https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions.
