### ISSUE TITLE
[custom images] Custom image creation should work with Python 3

### ISSUE THREAD

**Issue by AngusDavis** [GoogleCloudPlatform/cloud-dataproc#50]
The basestring type is not defined in Python 3 and attempting to create a custom image fails with:

> Traceback (most recent call last): File "generate_custom_image.py", line 419, in run() File "generate_custom_image.py", line 360, in run dataproc_base_image = get_dataproc_base_image(args.dataproc_version) File "generate_custom_image.py", line 98, in get_dataproc_base_image if stdout and isinstance(stdout, basestring): NameError: name 'basestring' is not defined

From:
https://stackoverflow.com/questions/50605530/unable-to-create-custom-image-for-dataproc

Alternatives for implementation:
http://python-future.org/compatible_idioms.html#basestring

**Comment by takeon8** [comment]
https://github.com/GoogleCloudPlatform/cloud-dataproc/pull/52
