### ISSUE TITLE
Requested disk size cannot be smaller than the image size (15 GB)

### ISSUE THREAD

**Issue by howie** [GoogleCloudPlatform/cloud-dataproc#63]
In  document and generate_custom_image.py both set default disk size to 10G.
But the API return size should large than 15G
[Daisy] Errors in one or more workflows:
  pvmax-spark-image: step "create-disks" run error: googleapi: Error 400: Invalid value for field 'resource.sizeGb': '10'. Requested disk size cannot be smaller than the image size (15 GB), invalid
Traceback (most recent call last):
  File "generate_custom_image.py", line 463, in <module>
    run()
  File "generate_custom_image.py", line 435, in run
    run_daisy(os.path.abspath(args.daisy_path), workflow)
  File "generate_custom_image.py", line 123, in run_daisy
    raise RuntimeError("Error building custom image.")
RuntimeError: Error building custom image.

**Comment by medb** [comment]
PR merged
