### ISSUE TITLE
[custom images] Allow user to change expiration time

### ISSUE THREAD

**Issue by howie** [GoogleCloudPlatform/cloud-dataproc#80]
I don't know why set exipre day after 30 days, and not open as an option ?
Do you have any concern ?
`
expiration_date = creation_date + datetime.timedelta(days=30)
  _LOG.info(
      constants.notify_expiration_text.format(args.image_name,
                                              str(expiration_date)))
`

**Comment by aniket486** [comment]
Thanks for the contribution, @howie. #81 is now merged.
