### ISSUE TITLE
Python3.6 support

### ISSUE THREAD

**Issue by kvudata** [GoogleCloudPlatform/cloud-dataproc#84]
I was once able to run PySpark jobs on python3.6 by installing the python3.6 Debian package (and other dependencies via `pip`) via a cluster init action, but it seems that no longer works.
It seems like the python3.6 package no longer installs pip, what is the a recommended way to use python3.6 in Dataproc? I've looked at installing it from source but it takes upwards of 30 minutes to bring up the cluster, not great when dynamically bringing up clusters as needed (would be idle most of the time otherwise).

Our cluster(s) are configured with the default (unspecified) version of Dataproc.

**Comment by howie** [comment]
Hi
You can create custom image (prebuild with python lib).

**Comment by functicons** [comment]
You can use the [conda init action](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/conda) to install Miniconda3 to get Python 3.6 in the cluster.

**Comment by kvudata** [comment]
Thanks for the help!
