### ISSUE TITLE
Spark 2.4

### ISSUE THREAD

**Issue by ShaunWang965475263** [GoogleCloudPlatform/cloud-dataproc#95]
Hello,

I am running the beta version image for spark 2.4 as our needs is to read AVRO format files. But the package on the documentation page says 
The spark-avro module is external and not included in spark-submit or spark-shell by default.

How do I include spark-avro module and google-cloud-bigquery module in the program ?

Thanks,
Shaun

**Comment by functicons** [comment]
It is documented in [Spark doc](https://spark.apache.org/docs/2.4.3/sql-data-sources-avro.html).

    ./bin/spark-submit --packages org.apache.spark:spark-avro_2.12:2.4.3 ...
