### ISSUE TITLE
Unable To Install Hive On Custom Image

### ISSUE THREAD

**Issue by altaetran** [GoogleCloudPlatform/cloud-dataproc#99]
Hi, 

I am working with custom images for dataproc using the daisy workflow, but I also would like to configure Hive to work with my clusters. However, I am unable to do so, as the only posted way to integrate Hive in dataproc is through initialization scripts, which cannot be run when custom images are used. Does anyone know how I might be able to configure Hive? Thanks!

**Comment by medb** [comment]
Hive is installed on all Dataproc images, you can use it after cluster creation by running `hive` command on master node, or submitting [Hive job](https://cloud.google.com/sdk/gcloud/reference/dataproc/jobs/submit/hive) through Dataproc Jobs API.

**Comment by altaetran** [comment]
Thank you for the prompt reply! I am able to run jobs with Hive internally, but wasn't able to configure Hive to connect to an external metastore CloudSQL server as recommended by [Hive-on-cloud-dataproc](https://cloud.google.com/solutions/using-apache-hive-on-cloud-dataproc)

**Comment by medb** [comment]
You should be able to follow instructions in [Using Apache Hive on Cloud Dataproc](https://cloud.google.com/solutions/using-apache-hive-on-cloud-dataproc) and [Cloud SQL I/O and Hive Metastore](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/tree/master/cloud-sql-proxy#cloud-sql-io-and-hive-metastore).

Feel free to file issues in [init actions](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions) repo if you will face any obstacles.

**Comment by medb** [comment]
If you want to configure CloudSQL proxy in custom image, you should be able to configure it by copying relevant parts from [init action script](https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/cloud-sql-proxy/cloud-sql-proxy.sh) and run them as custom image script.
